### ISSUE TITLE
How to compile on macOS M1?

### ISSUE THREAD

**Issue by KenjutsuGH** [c-sky/toolchain-build#6]
Is it possible to build this toolchain under **macOS** on a M1?

I ran the script as: 

`./build-csky-gcc.py csky-gcc --src ./ --triple csky-unknown-elf`

but it eventually gives the error:

`configure: error: Building GCC requires GMP 4.2+, MPFR 3.1.0+ and MPC 0.8.0+.`

I have **GMP**, **MPFR** and **MPC** installed via **brew**:

```
brew list gmp
/opt/homebrew/Cellar/gmp/6.2.1_1/include/ (2 files)
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmpxx.4.dylib
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/pkgconfig/ (2 files)
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/ (4 other files)
/opt/homebrew/Cellar/gmp/6.2.1_1/share/info/ (3 files)
```

```
brew list mpfr
/opt/homebrew/Cellar/mpfr/4.2.0/include/ (2 files)
/opt/homebrew/Cellar/mpfr/4.2.0/lib/libmpfr.6.dylib
/opt/homebrew/Cellar/mpfr/4.2.0/lib/pkgconfig/mpfr.pc
/opt/homebrew/Cellar/mpfr/4.2.0/lib/ (2 other files)
/opt/homebrew/Cellar/mpfr/4.2.0/share/doc/ (14 files)
/opt/homebrew/Cellar/mpfr/4.2.0/share/info/mpfr.info
```
```
brew list mpc
/opt/homebrew/Cellar/mpc/0.34/bin/mpc
/opt/homebrew/Cellar/mpc/0.34/etc/bash_completion.d/mpc
/opt/homebrew/Cellar/mpc/0.34/share/doc/ (6 files)
```

**Comment by wdyichen** [comment]
> Is it possible to build this toolchain under **macOS** on a M1?
> 
> I ran the script as:
> 
> `./build-csky-gcc.py csky-gcc --src ./ --triple csky-unknown-elf`
> 
> but it eventually gives the error:
> 
> `configure: error: Building GCC requires GMP 4.2+, MPFR 3.1.0+ and MPC 0.8.0+.`
> 
> I have **GMP**, **MPFR** and **MPC** installed via **brew**:
> 
> ```
> brew list gmp
> /opt/homebrew/Cellar/gmp/6.2.1_1/include/ (2 files)
> /opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib
> /opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmpxx.4.dylib
> /opt/homebrew/Cellar/gmp/6.2.1_1/lib/pkgconfig/ (2 files)
> /opt/homebrew/Cellar/gmp/6.2.1_1/lib/ (4 other files)
> /opt/homebrew/Cellar/gmp/6.2.1_1/share/info/ (3 files)
> ```
> 
> ```
> brew list mpfr
> /opt/homebrew/Cellar/mpfr/4.2.0/include/ (2 files)
> /opt/homebrew/Cellar/mpfr/4.2.0/lib/libmpfr.6.dylib
> /opt/homebrew/Cellar/mpfr/4.2.0/lib/pkgconfig/mpfr.pc
> /opt/homebrew/Cellar/mpfr/4.2.0/lib/ (2 other files)
> /opt/homebrew/Cellar/mpfr/4.2.0/share/doc/ (14 files)
> /opt/homebrew/Cellar/mpfr/4.2.0/share/info/mpfr.info
> ```
> 
> ```
> brew list mpc
> /opt/homebrew/Cellar/mpc/0.34/bin/mpc
> /opt/homebrew/Cellar/mpc/0.34/etc/bash_completion.d/mpc
> /opt/homebrew/Cellar/mpc/0.34/share/doc/ (6 files)
> ```

you can use `brew install libmpc`, then auto install deps gmp mpfr.

maybe exist DOT error when compiling gdb, so use  `./build-csky-gcc.py csky-gcc --src ./ --triple csky-unknown-elf --disable-gdb`。

When I finished compiling successfully, csky-unknown-elf-gcc worked, but csky-unknown-elf-gcc didn't support generating map files with -wl, and it didn't handle things like attribute(isr) properly. Anyway, it compiled things. But this thing won't work properly on the target.

Therefore, it is not recommended to try, and expect to release the release version after the official self-test is passed.

**Comment by KenjutsuGH** [comment]
Thank you for the feedback.

`brew install libmpc` gives:

```
Warning: libmpc 1.3.1 is already installed and up-to-date.
To reinstall 1.3.1, run:
  brew reinstall libmpc
```

And `/build-csky-gcc.py csky-gcc --src ./ --triple csky-unknown-elf --disable-gdb` also gives 

```
configure: error: Building GCC requires GMP 4.2+, MPFR 3.1.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
```

But if I understand correctly, there will be a macOS version soon?

**Comment by wdyichen** [comment]
> configure: error: Building GCC requires GMP 4.2+, MPFR 3.1.0+ and MPC 0.8.0+.
> Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify

you can use
`brew list --version` show lib's version,

ex my info:
`gmp 6.2.1_1`
`libmpc 1.3.1`
`mpfr 4.2.0`


so I think your libs version < GMP 4.2+, MPFR 3.1.0+ and MPC 0.8.0+，
upgrade it.

**Comment by KenjutsuGH** [comment]
Thank you for the reply.

```
brew list --version gmp libmpc mpfr
gmp 6.2.1_1
libmpc 1.3.1
mpfr 4.2.0
```
Still the same compile error.

**Comment by crosstyan** [comment]
You have to specify `--with-gmp=$GMP_PATH --with-mpfr=$MPFR_PATH --with-mpc=$LIBMPC_PATH` just like [my build.sh](https://github.com/crosstyan/Xuantie-800-gcc-elf-newlib-prebuilt/blob/edeee077716171cdf41e859078aba45d36586389/build.sh#LL15C109-L15C112) with the output of  `build-csky-gcc.py` following with `--fake` parameter. 

You could find these path with `brew info <gmp|mpfr|libmpc>` and I have a prebuilt binary release [here](https://github.com/crosstyan/Xuantie-800-gcc-elf-newlib-prebuilt/releases/tag/v0.1).

**Comment by KenjutsuGH** [comment]
Thank you! Much easier to download your prebuilt toolchain than to wait hours for it to build
